version: '3.9'

services:
  mysql-db:
    build:
      context: ./mysql-db
    restart: always
    volumes:
      - docker_db_data:/var/lib/demosql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-h", "127.0.0.1", "-u", "taa", "-p4141", "-e", "SELECT COUNT(*) FROM logsDB.Logs;"]
      interval: 60s
      timeout: 12s
      retries: 10

  logs-service:
    build:
      context: ./logs-service
    restart: always
    depends_on:
      - mysql-db
    ports:
      - "5001:5001"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:5001/api/logs"]
      interval: 30s
      retries: 10

  springboot-service:
    build:
      context: ./springboot-service
    restart: always
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080/visits"]
      interval: 30s
      retries: 10

  stats-service:
    build:
      context: ./stats-service
    restart: always
    depends_on:
      - springboot-service
      - logs-service
    ports:
      - "8000:8000"

volumes:
  docker_db_data:
