version: 2.1
orbs:
  node: circleci/node@7.1.0
  python: circleci/python@3.0.0
jobs:
  test-node:
    # Install node dependencies and run tests
    executor: node/default
    working_directory: ~/project/logs-service
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test --passWithNoTests
  test-java:
    docker:
      - image: cimg/openjdk:23.0.2
    working_directory: ~/project/springboot-service
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: mvn verify
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository
  test-python:
    # Install dependencies and run tests yes
    docker:
      - image: cimg/python:3.13.2
    working_directory: ~/project/stats-service
    steps:
      - checkout:
          path: ~/project
      - python/install-packages
      - run:
          name: Run tests
          command: python manage.py test
workflows:
  build-and-test:
    jobs:
      - test-node
      - test-java
      - test-python